ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "passwordChangedAt" TIMESTAMP(3);

ALTER TABLE "UserPreference" ADD COLUMN IF NOT EXISTS "sidebarDefault" TEXT NOT NULL DEFAULT 'expanded';
ALTER TABLE "UserPreference" ADD COLUMN IF NOT EXISTS "projectSelectorBehavior" TEXT NOT NULL DEFAULT 'remember';
ALTER TABLE "UserPreference" ADD COLUMN IF NOT EXISTS "rememberLastSpace" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "UserPreference" ADD COLUMN IF NOT EXISTS "emailNotifications" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "UserPreference" ADD COLUMN IF NOT EXISTS "inAppNotifications" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "UserPreference" ADD COLUMN IF NOT EXISTS "dueSoonNotifications" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "UserPreference" ADD COLUMN IF NOT EXISTS "assignmentNotifications" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "UserPreference" ADD COLUMN IF NOT EXISTS "mentionNotifications" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "UserPreference" ADD COLUMN IF NOT EXISTS "commentNotifications" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "UserPreference" ADD COLUMN IF NOT EXISTS "digestFrequency" TEXT NOT NULL DEFAULT 'daily';
ALTER TABLE "UserPreference" ADD COLUMN IF NOT EXISTS "quietHoursEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "UserPreference" ADD COLUMN IF NOT EXISTS "quietHoursStart" TEXT NOT NULL DEFAULT '18:00';
ALTER TABLE "UserPreference" ADD COLUMN IF NOT EXISTS "quietHoursEnd" TEXT NOT NULL DEFAULT '09:00';
